# Generated by Django 4.2 on 2024-12-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
